### ISSUE TITLE
Upcoming schedule

### ISSUE THREAD

**Issue by mairaw** [IEvangelist/DotNetDocs.Show#18]
For me, it was a bit of a surprise that the upcoming schedule button on the homepage and https://dotnetdocs.dev/schedule lists the upcoming shows in descending order. I'd expect to see the next one first and not last.

**Comment by IEvangelist** [comment]
The column has a chevron that enables the user to toggle, descending or ascending - click to toggle. I'm a bit torn, but let's solicit @scottaddie and @CamSoper thoughts on this too?

**Comment by CamSoper** [comment]
@IEvangelist Right, but @mairaw is talking the grid view on the main page, right? When you click to show the upcoming episodes on the schedule?

**Comment by mairaw** [comment]
No option on this view:
![image](https://user-images.githubusercontent.com/12971179/86952366-be4ef980-c107-11ea-97c4-6be72c755f9b.png)

But I think the default view should be the opposite.

**Comment by scottaddie** [comment]
I'm in agreement with Maira. I think those dates should be listed in ascending order.

**Comment by IEvangelist** [comment]
For the main page,  that is a design decision... we start with the future shows being collapsed. So that the focus is the next show. Past shows show in descending order, latest to oldest. Then the future shows follow that. But on the schedule page, it's something that can be toggled. Would you expect to see the future shows on the main page in ascending order?

**Comment by mairaw** [comment]
Past shows is fine to show the way you are because you want to see the newest first. But yes, I'd expect to see future shows on the main page in ascending order. And I'd expect to see the default listing to be ascending in the schedule page too.

**Comment by IEvangelist** [comment]
Fixed in https://github.com/IEvangelist/DotNetDocs.Show/commit/294681ca2daab0f5edecd689974fb0c6e42b07ef
