### ISSUE TITLE
The .NET Docs Show: transitioning to .NET properties / community standup

### ISSUE THREAD

**Issue by IEvangelist** [IEvangelist/DotNetDocs.Show#22]
As a follow up from a conversation with @jamesmontemagno, and @scottaddie. In order to smoothly transition from https://dotnetdocs.dev to https://dot.net, we'll need to complete the following tasks as a minimum:

- [x] Reach out to all future scheduled guests
- [x] Update all future shows
   - Show dates move to Monday's
   - Update calendar invites
       - Each DB entry has an updated `.GuestStreamUrl`
- [x] Formalize hosting rotation (2/3 hosts per show)
   - @cecilphillip and @mairaw to join the hosting rotation 🎉 
- [ ] ~~Decommission Azure resources~~
- [ ] Finalize cutover date
   - Tentatively thinking 1 month out - targeting 8/24 as first Monday of new schedule
- [x] Update link on dot.net/community site
- [x] Determine whether or not we should keep our Twitch, YouTube, and Twitter accounts?

> Work with @mairaw on updates to the existing dot.net site, including efforts for .NET TV

**Comment by IEvangelist** [comment]
Tracking email communications here:
https://gist.github.com/IEvangelist/203156d50603005c023cb5910666989c#gistcomment-3404323

**Comment by jamesmontemagno** [comment]
Lovely! We are starting to finalize the backend for integrating into multiple playlists and for guests functionality. We are ready on StreamYard/Restream to everything in.

Thoughts:
* Keep your website as is for now, but just show the new .NET playlist we create  and the Visual Studio Twitch. We can re-upload older content to the .NET YouTube as well.

**Comment by jamesmontemagno** [comment]
Hey @IEvangelist  I don't think you should link to that as it has PII in it..

**Comment by IEvangelist** [comment]
> Hey @IEvangelist I don't think you should link to that as it has PII in it..

Removed 👍🏼

**Comment by IEvangelist** [comment]
It will require a bit of re-work to pull data from another data source. Where is that coming from now on your end, do you have examples I could reference? Is any of that protected behind auth/tokens/jwt/etc?

**Comment by IEvangelist** [comment]
> Lovely! We are starting to finalize the backend for integrating into multiple playlists and for guests functionality. We are ready on StreamYard/Restream to everything in.
> 
> Thoughts:
> 
> * Keep your website as is for now, but just show the new .NET playlist we create  and the Visual Studio Twitch. We can re-upload older content to the .NET YouTube as well.

Hi @jamesmontemagno 

It will require a bit of re-work to pull data from another source. Where is that coming from now on your end, do you have examples I could reference? Is any of that protected behind auth/tokens/jwt/etc? And what data points are available - I'm assuming there will be some gaps?

**Comment by scottaddie** [comment]
@IEvangelist I think the API James is referencing is being built over at https://github.com/dotnet/website-community-standup-api.

**Comment by jamesmontemagno** [comment]
Let's jump on a call to walk through your backend.
