### ISSUE TITLE
https://www.twitch.tv/thedotnetdocs does not exist

### ISSUE THREAD

**Issue by icnocop** [IEvangelist/DotNetDocs.Show#31]
Hi.

I noticed there are links to https://www.twitch.tv/thedotnetdocs but that twitch channel doesn't exist.

There's a "Remind me" button on https://dotnetdocs.dev/ that has a link to https://www.twitch.tv/thedotnetdocs but I'm thinking it should actually point to https://www.twitch.tv/visualstudio instead.

**Comment by IEvangelist** [comment]
Addressed in 8180afe
